//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScottyApps.WCFPractice.CalcService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Complex", Namespace="http://schemas.datacontract.org/2004/07/ScottyApps.WCFPractice.CalcService")]
    public partial class Complex : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private double ImaginaryField;
        
        private double RealField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Imaginary
        {
            get
            {
                return this.ImaginaryField;
            }
            set
            {
                this.ImaginaryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Real
        {
            get
            {
                return this.RealField;
            }
            set
            {
                this.RealField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ICalcService")]
public interface ICalcService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcService/Add", ReplyAction="http://tempuri.org/ICalcService/AddResponse")]
    ScottyApps.WCFPractice.CalcService.Complex Add(ScottyApps.WCFPractice.CalcService.Complex x, ScottyApps.WCFPractice.CalcService.Complex y);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcService/Subtract", ReplyAction="http://tempuri.org/ICalcService/SubtractResponse")]
    ScottyApps.WCFPractice.CalcService.Complex Subtract(ScottyApps.WCFPractice.CalcService.Complex x, ScottyApps.WCFPractice.CalcService.Complex y);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcService/Multiply", ReplyAction="http://tempuri.org/ICalcService/MultiplyResponse")]
    ScottyApps.WCFPractice.CalcService.Complex Multiply(ScottyApps.WCFPractice.CalcService.Complex x, ScottyApps.WCFPractice.CalcService.Complex y);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcService/Devide", ReplyAction="http://tempuri.org/ICalcService/DevideResponse")]
    ScottyApps.WCFPractice.CalcService.Complex Devide(ScottyApps.WCFPractice.CalcService.Complex x, ScottyApps.WCFPractice.CalcService.Complex y);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ICalcServiceChannel : ICalcService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class CalcServiceClient : System.ServiceModel.ClientBase<ICalcService>, ICalcService
{
    
    public CalcServiceClient()
    {
    }
    
    public CalcServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public CalcServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CalcServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CalcServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public ScottyApps.WCFPractice.CalcService.Complex Add(ScottyApps.WCFPractice.CalcService.Complex x, ScottyApps.WCFPractice.CalcService.Complex y)
    {
        return base.Channel.Add(x, y);
    }
    
    public ScottyApps.WCFPractice.CalcService.Complex Subtract(ScottyApps.WCFPractice.CalcService.Complex x, ScottyApps.WCFPractice.CalcService.Complex y)
    {
        return base.Channel.Subtract(x, y);
    }
    
    public ScottyApps.WCFPractice.CalcService.Complex Multiply(ScottyApps.WCFPractice.CalcService.Complex x, ScottyApps.WCFPractice.CalcService.Complex y)
    {
        return base.Channel.Multiply(x, y);
    }
    
    public ScottyApps.WCFPractice.CalcService.Complex Devide(ScottyApps.WCFPractice.CalcService.Complex x, ScottyApps.WCFPractice.CalcService.Complex y)
    {
        return base.Channel.Devide(x, y);
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IEcho")]
public interface IEcho
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEcho/Echo", ReplyAction="http://tempuri.org/IEcho/EchoResponse")]
    string Echo(string msg);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IEcho/SayHello")]
    void SayHello(string name);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IEchoChannel : IEcho, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class EchoClient : System.ServiceModel.ClientBase<IEcho>, IEcho
{
    
    public EchoClient()
    {
    }
    
    public EchoClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public EchoClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public EchoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public EchoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string Echo(string msg)
    {
        return base.Channel.Echo(msg);
    }
    
    public void SayHello(string name)
    {
        base.Channel.SayHello(name);
    }
}
